book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('list/', views.list_all, name='list_all'),
    path('detail/<int:book_id>/', views.book_detail, name='detail'),
    path('update/<int:book_id>/', views.update, name='update'),
    path('delete/<int:book_id>/', views.delete, name='delete'),
    path('', views.create, name='create'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import index

urlpatterns = [
    path('author/', include('author.urls', namespace='author')),
    path('admin/', admin.site.urls),
    path('book/', include('book.urls', namespace='book')),
    path('user/', include('authentication.urls', namespace='authentication')),
    path('order/', include('order.urls', namespace='order')),
    path('', index, name='index')
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.create_order, name='create_order'),
    path('borrow_book/<int:book_id>/', views.borrow_book, name='borrow_book'),
    path('close_order/<int:order_id>/', views.close_order, name='close_order'),
    path('list/', views.view_all_orders, name='view_all_orders'),
    path('update/<int:order_id>/', views.update_order, name='update_order'),
    path('delete/<int:order_id>/', views.delete_order, name='delete_order'),
    path('detail/<int:order_id>/', views.detail_order, name='detail_order'),
]

order/models.py
from django.db import models, DataError, IntegrityError

from authentication.models import CustomUser
from author.models import Author
from book.models import Book
from datetime import timedelta
from django.utils import timezone


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    end_at = models.DateTimeField(null=True)
    plated_end_at = models.DateTimeField(default=timezone.now() + timedelta(days=10))

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        return str(self.to_dict())[1:-1]

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'
    def to_dict(self):

        return {
            'id': self.id,
            'user': self.user,
            'book': self.book,
            'created_at': str(self.created_at),
            'end_at': str(self.end_at) if self.end_at else self.end_at,
            'plated_end_at': str(self.plated_end_at)
        }

    @staticmethod
    def create(user, book, plated_end_at):

        order = Order(user=user, book=book, plated_end_at=plated_end_at)
        if book.count <= len([order for order in Order.get_not_returned_books() if order.book.id == book.id]):
            return
        try:
            order.save()
            return order
        except (IntegrityError, AttributeError, DataError, ValueError) as err:
            # print(err)
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    @staticmethod
    def get_by_id(order_id):

        try:
            user = Order.objects.get(id=order_id)
            return user
        except Order.DoesNotExist:
            pass

    def update(self, plated_end_at=None, end_at=None):
        if plated_end_at:
            self.plated_end_at = plated_end_at
        if end_at:
            self.end_at = end_at
        self.save()

    @staticmethod
    def get_all():
        all_order = list(Order.objects.all())
        return all_order

    @staticmethod
    def get_not_returned_books():
        orders = [order for order in Order.get_all() if order.end_at is None]
        return orders

    @staticmethod
    def delete_by_id(order_id):
        """
        :param user_id: an id of a user to be deleted
        :type user_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            user = Order.objects.get(id=order_id)
            user.delete()
            return True
        except Order.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

order/forms.py
from django import forms
from .models import *


class CreateOrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].empty_label = 'Please select a user'
        self.fields['book'].empty_label = 'Please select a book'

    class Meta:
        model = Order
        fields = ['user', 'book']

    def clean_book(self):
        book = self.cleaned_data.get('book')
        if book.count <= 1:
            raise forms.ValidationError('There is the last book in our library. Please try to order it later')
        return book


class UpdateOrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['end_at', 'plated_end_at']
        widgets = {
            'end_at': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'plated_end_at': forms.DateTimeInput()
        }

order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Order
from .forms import CreateOrderForm, UpdateOrderForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone


@login_required(login_url='authentication:login')
def view_all_orders(request):
    if request.user.role != 1:
        return redirect('authentication:denied')
    order_list = Order.objects.all()
    return render(request, 'order/orders_list.html', {'order_list': order_list})


@login_required(login_url='authentication:login')
def detail_order(request, order_id):
    if request.user.role != 1:
        return redirect('authentication:denied')
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/detail.html', {'order': order})


@login_required(login_url='authentication:login')
def create_order(request):
    if request.user.role != 1:
        return redirect('authentication:denied')
    if request.method == 'POST':
        form = CreateOrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.book.count -= 1
            order.book.save()
            order.save()
            return redirect('order:view_all_orders')
    else:
        form = CreateOrderForm()
    return render(request, 'order/create.html', {'form': form})


@login_required(login_url='authentication:login')
def update_order(request, order_id):
    if request.user.role != 1:
        return redirect('authentication:denied')
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        form = UpdateOrderForm(instance=order, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('order:view_all_orders')
    else:
        form = UpdateOrderForm(instance=order)
    return render(request, 'order/update.html', {'form': form})


@login_required(login_url='authentication:login')
def delete_order(request, order_id):
    if request.user.role != 1:
        return redirect('authentication:denied')
    order = get_object_or_404(Order, id=order_id)
    order.book.count += 1
    order.book.save()
    order.delete()
    return redirect('order:view_all_orders')


@login_required(login_url='authentication:login')
def borrow_book(request, book_id):
    order = Order(book_id=book_id, user_id=request.user.id)
    order.book.count -= 1
    order.book.save()
    order.save()
    return redirect('authentication:detail', user_id=request.user.id)


@login_required(login_url='authentication:login')
def close_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.user.role != 1 and request.user.id != order.user.id:
        return redirect('authentication:denied')
    order.end_at = timezone.now()
    order.book.count += 1
    order.book.save()
    order.save()
    return redirect('authentication:detail', user_id=order.user.id)

order/templates/order/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Create new order {% endblock title %}
{% block content %}
    <a href="{% url 'order:view_all_orders' %}">←Back to all orders</a>
    <p></p>
    <h3>Create new order</h3>
    <form method="post" autocomplete="off">
        <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
            {% csrf_token %}
            {{ form|crispy }}
            <p></p>
        </div>
        <p><button type="submit" class="btn btn-success">Create order</button></p>
    </form>
{% endblock content %}

order/templates/order/detail.html
{% extends 'base.html' %}

{% block title %} Order №{{ order.id }} {% endblock title %}

{% block content %}
    <a href="{% url 'order:view_all_orders' %}">←Back</a>
    <p></p>
    <h3>Order №{{ order.id }}</h3>
    <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
        <p></p>
        <p><b>User:</b> <a href="{% url 'authentication:detail' order.user.id %}">{{ order.user.first_name }} {{ order.user.last_name }}</a></p>
        <p><b>Book:</b> <a href="{% url 'book:detail' order.book.id %}">{{ order.book.name }}</a></p>
        <p><b>Book taken on:</b> {{ order.created_at }}</p>
        {% if order.end_at %}
            <p><b>Was returned on:</b> {{ order.end_at }}</p>
        {% else %}
            <p><b>Must be returned on:</b> {{ order.plated_end_at }}</p>
        {% endif %}
        <p></p>
    </div>
    {% if user.role == 1 and not order.end_at %}
        <a href="{% url 'order:close_order' order.id %}"><button type="button" class="btn btn-primary">Close order</button></a>
        <a style="padding-left: 10px;" href="{% url 'order:update_order' order.id %}"><button type="button" class="btn btn-secondary">Update</button></a>
        <a style="padding-left: 10px;" href="{% url 'order:delete_order' order.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
    {% endif %}
{% endblock content %}

order/templates/order/orders_list.html
{% extends 'base.html' %}

{% block title %} All Orders {% endblock title %}

{% block content %}
    <h2 style="text-align: center">All orders:</h2>
    {% if user.role == 1 %}
        <a href="{% url 'order:create_order' %}"><button type="button" class="btn btn-success">Create order</button></a>
    {% endif %}
    {% for order in order_list %}
        <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
                <p><h5><a href="{% url 'order:detail_order' order.id %}"> Order №{{ order.id }}</a></h5></p>
                <p><b>User:</b> <a href="{% url 'authentication:detail' order.user.id %}">{{ order.user.first_name }} {{ order.user.last_name }}</a></p>
                <p><b>Book:</b> <a href="{% url 'book:detail' order.book.id %}">{{ order.book.name }}</a></p>
                {% for author in order.book.authors.all %}
                    <li>Authors: <a href="{% url 'author:detail' author.id %}"> {{ author.name }} {{ author.surname }}</a></li>
                {% endfor %}
                <p></p>
        </div>
        {% if user.role == 1 and not order.end_at%}
            <a href="{% url 'order:close_order' order.id %}"><button type="button" class="btn btn-primary">Close order</button></a>
            <a style="padding-left: 10px;" href="{% url 'order:update_order' order.id %}"><button type="button" class="btn btn-secondary">Update</button></a>
            <a style="padding-left: 10px;" href="{% url 'order:delete_order' order.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
        {% endif %}
    {% endfor %}

{% endblock content %}

order/templates/order/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Update order {% endblock title %}
{% block content %}
    <a href="{% url 'order:view_all_orders' %}">←Back to all orders</a>
    <p></p>
    <h3>Update order</h3>
    <form method="post">
        <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
            {% csrf_token %}
            {{ form|crispy }}
            <p></p>
        </div>
        <button type="submit" class="btn btn-success">Update order</button>
    </form>
{% endblock content %}