author/urls.py
from django.urls import path
from . import views

app_name = 'author'

urlpatterns = [
    path('delete/<int:author_id>/', views.delete_author, name='delete'),
    path('detail/<int:author_id>/', views.author_detail, name='detail'),
    path('update/<int:author_id>/', views.update_author, name='update'),
    path('list/', views.authors_list, name='list'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('list/', views.list_all, name='list_all'),
    path('detail/<int:book_id>/', views.book_detail, name='detail'),
    path('update/<int:book_id>/', views.update, name='update'),
    path('delete/<int:book_id>/', views.delete, name='delete'),
    path('', views.create, name='create'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import index

urlpatterns = [
    path('author/', include('author.urls', namespace='author')),
    path('admin/', admin.site.urls),
    path('book/', include('book.urls', namespace='book')),
    path('user/', include('authentication.urls', namespace='authentication')),
    path('order/', include('order.urls', namespace='order')),
    path('', index, name='index')
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.create_order, name='create_order'),
    path('borrow_book/<int:book_id>/', views.borrow_book, name='borrow_book'),
    path('close_order/<int:order_id>/', views.close_order, name='close_order'),
    path('list/', views.view_all_orders, name='view_all_orders'),
    path('update/<int:order_id>/', views.update_order, name='update_order'),
    path('delete/<int:order_id>/', views.delete_order, name='delete_order'),
    path('detail/<int:order_id>/', views.detail_order, name='detail_order'),
]

author/models.py
from django.db import models, IntegrityError, DataError


class Author(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes last name of the author
        type surname: str max_length=20
        param patronymic: Describes middle name of the author
        type patronymic: str max_length=20

    """

    name = models.CharField(blank=True, max_length=20)
    surname = models.CharField(blank=True, max_length=20)
    patronymic = models.CharField(blank=True, max_length=20)

    def __str__(self):
        """
        Magic method is redefined to show all information about Author.
        :return: author id, author name, author surname, author patronymic
        """
        return str(self.name + " " + self.patronymic + " " + self.surname)

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Author object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    @staticmethod
    def get_by_id(author_id):
        """
        :param author_id: SERIAL: the id of a Author to be found in the DB
        :return: author object or None if a user with such ID does not exist
        """
        try:
            user = Author.objects.get(id=author_id)
            return user
        except Author.DoesNotExist:
            pass
            # LOGGER.error("User does not exist")

    @staticmethod
    def delete_by_id(author_id):
        """
        :param author_id: an id of a author to be deleted
        :type author_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            author = Author.objects.get(id=author_id)
            author.delete()
            return True
        except Author.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

    @staticmethod
    def create(name, surname, patronymic):
        """
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: a new author object which is also written into the DB
        """
        author = Author(name=name, surname=surname, patronymic=patronymic)
        try:
            author.save()
            return author
        except (IntegrityError, AttributeError, DataError):
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    def to_dict(self):
        """
        :return: author id, author name, author surname, author patronymic
        :Example:
        | {
        |   'id': 8,
        |   'name': 'fn',
        |   'surname': 'mn',
        |   'patronymic': 'ln',
        | }
        """

        return {
            'id': self.id,
            'name': self.name,
            'surname': self.surname,
            'patronymic': self.patronymic
        }

    def update(self,
               name=None,
               surname=None,
               patronymic=None):
        """
        Updates author in the database with the specified parameters.\n
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: None
        """

        if name:
            self.name = name
        if surname:
            self.surname = surname
        if patronymic:
            self.patronymic = patronymic
        try:
            from django.db import transaction
            with transaction.atomic():
                self.save()
        except:
            pass

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all authors
        """
        all_users = Author.objects.all()
        return all_users

author/forms.py
from django import forms
from .models import Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'surname', 'patronymic']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) == 0:
            raise forms.ValidationError('Name must be filled')
        return name

    def clean_surname(self):
        surname = self.cleaned_data.get('surname')
        if len(surname) == 0:
            raise forms.ValidationError('Surname must be filled')
        return surname

author/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Author
from .forms import AuthorForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='authentication:login')
def authors_list(request):
    authors = Author.get_all()
    if request.method == 'POST':
        if request.user.role != 1:
            return redirect('authentication:denied')
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('author:list')
    else:
        form = AuthorForm()
    return render(request, 'author/author.html', {'authors': authors,
                                                  'form': form})


@login_required(login_url='authentication:login')
def author_detail(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    books = author.books.all()
    return render(request, 'author/detail.html', {'author': author,
                                                  'books': books})


@login_required(login_url='authentication:login')
def update_author(request, author_id):
    if request.user.role != 1:
        return redirect('authentication:denied')
    author = get_object_or_404(Author, id=author_id)
    if request.POST:
        form = AuthorForm(instance=author, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('author:list')
    else:
        form = AuthorForm(instance=author)
        authors = Author.get_all()
    return render(request, 'author/author.html', {'form': form,
                                                  'authors': authors})


@login_required(login_url='authentication:login')
def delete_author(request, author_id):
    if request.user.role != 1:
        return redirect('authentication:denied')
    author = get_object_or_404(Author, id=author_id)
    author.delete()
    return redirect('author:list')

author/templates/author/author.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    {% if user.role == 1 %}
    <form method="post">
        {% csrf_token %}
        <table class="table">
            <thead>
                <th>{{ form.name|as_crispy_field }}</th>
                <th>{{ form.surname|as_crispy_field }}</th>
                <th valign="top">{{ form.patronymic|as_crispy_field }}</th>
            </thead>
        </table>
                <p align="center"><button style="height:40px;width:150px" type="submit" class="btn btn-success">Save</button></p>
    </form>
    {% endif %}
    <table class="table">
    <thead>
        <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Patronymic</th>
            <th></th>
            {% if user.role == 1 %}
            <th></th>
            <th></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for author in  authors %}
            <tr>
                <td>{{ author.name }}</td>
                <td>{{ author.surname }}</td>
                <td>{{ author.patronymic }}</td>
                <td><a href="{% url 'author:detail' author.id %}"><button type="button" class="btn btn-primary">Books</button></a></td>
                {% if user.role == 1 %}
                <td>
                    <a href="{% url 'author:update' author.id %}"><button type="button" class="btn btn-secondary">Edit</button></a>
                </td>
                <td>
                    <a href="{% url 'author:delete' author.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

author/templates/author/detail.html
{% extends 'base.html' %}

{% block title %} {{ author.name }} {{ author.surname }} {% endblock title %}

{% block content %}
    <h1 style="text-align: center">{{ author.name }} {{ author.surname }}'s books:</h1>
    {% if not books %}
        <p></p>
    <h3 style="text-align: center">We have no books written by {{ author.name }} {{ author.surname }} yet.</h3>
    {% endif %}
    {% for book in books %}
        <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
                <h5><a href="{% url 'book:detail' book.id %}">{{ book.name }}</a></h5>
                    <p><strong>Authors:</strong></p>
                    <ul style="list-style: none">
                        {% for author in book.authors.all %}
                            <li><a href="{% url 'author:detail' author.id %}">{{ author.name }} {{ author.surname }}</a></li>
                        {% endfor %}
                    </ul>
                <p><strong>Description: </strong> {{ book.description }}</p>
                <p><strong>Count: </strong> {{ book.count }}</p>
        </div>
                 {% if user.role == 1 %}
                    <a href="{% url 'book:update' book.id %}"><button type="button" class="btn btn-secondary">Update</button></a>
                    <a style="padding-left: 10px;" href="{% url 'book:delete' book.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
                 {% else %}
                     <a href="{% url 'order:borrow_book' book.id %}"><button type="button" class="btn btn-primary">Order book</button></a>
                 {% endif %}

    {% endfor %}

{% endblock content %}