book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('list/', views.list_all, name='list_all'),
    path('detail/<int:book_id>/', views.book_detail, name='detail'),
    path('update/<int:book_id>/', views.update, name='update'),
    path('delete/<int:book_id>/', views.delete, name='delete'),
    path('', views.create, name='create'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import index

urlpatterns = [
    path('author/', include('author.urls', namespace='author')),
    path('admin/', admin.site.urls),
    path('book/', include('book.urls', namespace='book')),
    path('user/', include('authentication.urls', namespace='authentication')),
    path('order/', include('order.urls', namespace='order')),
    path('', index, name='index')
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.create_order, name='create_order'),
    path('borrow_book/<int:book_id>/', views.borrow_book, name='borrow_book'),
    path('close_order/<int:order_id>/', views.close_order, name='close_order'),
    path('list/', views.view_all_orders, name='view_all_orders'),
    path('update/<int:order_id>/', views.update_order, name='update_order'),
    path('delete/<int:order_id>/', views.delete_order, name='delete_order'),
    path('detail/<int:order_id>/', views.detail_order, name='detail_order'),
]

book/models.py
from django.db import models, IntegrityError, DataError

from author.models import Author


class Book(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
    """

    name = models.CharField(blank=True, max_length=128)
    description = models.TextField(blank=True)
    count = models.IntegerField(default=10)
    authors = models.ManyToManyField(Author, related_name='books')

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        authors = [author.name + " " + author.surname for author in self.authors.all()]
        return str(self.name + " (" + str(authors)[1:-1] + ")")

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    @staticmethod
    def get_by_id(book_id):
        """
        :param book_id: SERIAL: the id of a Book to be found in the DB
        :return: book object or None if a book with such ID does not exist
        """
        try:
            user = Book.objects.get(id=book_id)
            return user
        except Book.DoesNotExist:
            pass
            # LOGGER.error("User does not exist")

    @staticmethod
    def delete_by_id(book_id):
        """
        :param book_id: an id of a book to be deleted
        :type book_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            book = Book.objects.get(id=book_id)
            book.delete()
            return True
        except Book.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

    @staticmethod
    def create(name, description, count=10, authors=None):
        """
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
        :return: a new book object which is also written into the DB
        """
        book = Book(name=name, description=description, count=count)
        try:
            book.save()
            if authors is not None:
                for author in authors:
                    book.authors.add(author)
            book.save()
            return book
        except (IntegrityError, AttributeError, DataError):
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    def to_dict(self):
        """
        :return: book id, book name, book description, book count, book authors
        :Example:
        | {
        |   'id': 8,
        |   'name': 'django book',
        |   'description': 'bla bla bla',
        |   'count': 10',
        |   'authors': []
        | }
        """

        return {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'count': self.count,
            'authors': [author.id for author in self.authors.all()]
        }

    def update(self, name=None, description=None, count=None):
        """
        Updates book in the database with the specified parameters.\n
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        :return: None
        """

        if name:
            self.name = name
        if description:
            self.description = description
        if count:
            self.count = count
        self.save()

    def add_authors(self, authors):
        """
        Add  authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """

        for author in authors:
            self.authors.add(author)
        self.save()

    def remove_authors(self, authors):
        """
        Remove authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        for author in authors:
            self.authors.remove(author)
        self.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all books
        """
        all_users = Book.objects.all()
        return list(all_users)

book/forms.py
from django import forms
from .models import Book


class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'description', 'count', 'authors']
        widgets = {
            'authors': forms.CheckboxSelectMultiple()
        }

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) == 0:
            raise forms.ValidationError('Name must be filled')
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if len(description) == 0:
            raise forms.ValidationError('Description must be filled')
        return description

    def clean_count(self):
        count = self.cleaned_data.get('count')
        if count < 0:
            raise forms.ValidationError('Count must be positive')
        return count

    # def clean_authors(self):
    #     authors = self.cleaned_data.get('authors')
    #     if authors is None:
    #         raise forms.ValidationError('You must select author')
    #     return authors

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book
from .forms import BookCreateForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='authentication:login')
def list_all(request):
    books_list = Book.objects.all()
    return render(request, 'book/list_all.html', {'books_list': books_list})

@login_required(login_url='authentication:login')
def book_detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'book/detail.html', {'book': book})

@login_required(login_url='authentication:login')
def create(request):
    if request.user.role != 1:
        return redirect('authentication:denied')
    if request.method == 'POST':
        form = BookCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book:list_all')
    else:
        form = BookCreateForm()
    return render(request, 'book/create.html', {'form': form})

@login_required(login_url='authentication:login')
def update(request, book_id):
    if request.user.role != 1:
        return redirect('authentication:denied')
    book = get_object_or_404(Book, id=book_id)
    if request.method == 'POST':
        form = BookCreateForm(instance=book, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('book:list_all')
    else:
        form = BookCreateForm(instance=book)
    return render(request, 'book/update.html', {'form': form})

@login_required(login_url='authentication:login')
def delete(request, book_id):
    if request.user.role != 1:
        return redirect('authentication:denied')
    book = get_object_or_404(Book, id=book_id)
    book.delete()
    return redirect('book:list_all')

book/templates/book/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add new book {% endblock title %}
{% block content %}
     <a href="{% url 'book:list_all' %}">←Back to all books</a>
    <P></P>
 <h3>Add new book</h3>
<form method="post" autocomplete="off">
    <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
    {% csrf_token %}
    {{ form|crispy }}
    <p></p>
    </div>
    <button type="submit" class="btn btn-success">Add book</button>
</form>
{% endblock content %}

book/templates/book/detail.html
{% extends 'base.html' %}

{% block title %} {{ book.name }} {% endblock title %}

{% block content %}
    <a href="{% url 'book:list_all' %}">←To all books</a>
    <p></p>
    <h3>{{ book.name }}</h3>
    <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
    <p></p>
    <p><strong>Authors:</strong></p>
    <ul style="list-style: none">
    {% for author in book.authors.all %}
    <li><a href="{% url 'author:detail' author.id %}">{{ author.name }} {{ author.surname }}</a></li>
    {% endfor %}
    </ul>
    <p><strong>Description: </strong> {{ book.description }}</p>
    <p><strong>Count: </strong>{{ book.count }}</p>
    </div>
    {% if user.role == 1 %}
        <a href="{% url 'book:update' book.id %}"><button type="button" class="btn btn-secondary">Update</button></a>
        <a style="padding-left: 10px;" href="{% url 'book:delete' book.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
    {% elif user.role == 0 and book.count > 1%}
        <a href="{% url 'order:borrow_book' book.id %}"><button type="button" class="btn btn-primary">Order Book</button></a>
    {% elif user.role == 0 and book.count <= 1 %}
        <p>This book is not available at the moment, try to order it later.</p>
    {% endif %}
{% endblock %}

book/templates/book/list_all.html
{% extends 'base.html' %}

{% block title %} All Books {% endblock title %}

{% block content %}
    <h1 style="text-align: center">All books:</h1>
    {% if user.role == 1 %}
        <a href="{% url 'book:create' %}"><button type="button" class="btn btn-success">Add Book</button></a>
    {% endif %}
    {% for book in books_list %}
        <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
                <h5><a href="{% url 'book:detail' book.id %}">{{ book.name }}</a></h5>
                    <p><strong>Authors:</strong></p>
                    <ul style="list-style: none">
                        {% for author in book.authors.all %}
                            <li><a href="{% url 'author:detail' author.id %}">{{ author.name }} {{ author.surname }}</a></li>
                        {% endfor %}
                    </ul>
                <p><strong>Description: </strong> {{ book.description }}</p>
                <p><strong>Count: </strong>{{ book.count }}</p>
        </div>
        {% if user.role == 1 %}
            <a href="{% url 'book:update' book.id %}"><button type="button" class="btn btn-secondary">Update</button></a>
            <a style="padding-left: 10px;" href="{% url 'book:delete' book.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
        {% endif %}
    {% endfor %}

{% endblock content %}

book/templates/book/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Update book {% endblock title %}
{% block content %}
    <a href="{% url 'book:list_all' %}">←Back to all books</a>
    <p></p>
 <h3>Update book</h3>
<form method="post">
    <div class="container" style="border: 1px solid cornflowerblue; border-radius: 5px; margin-top: 25px; margin-bottom: 20px; padding: 10px">
    {% csrf_token %}
    {{ form|crispy }}
    </div>
     <button type="submit" class="btn btn-success">Update book</button>
</form>
{% endblock content %}